### ISSUE TITLE
Failed Pokemon Go detection

### ISSUE THREAD

**Issue by clburlison** [clburlison/dmon#3]
## Bug
The following method of detecting if Pokemon Go is running is flawed

https://github.com/clburlison/dmon/blob/d873255fe427dd29039f0ddb44ad83aaadc9e9e9/src/usr/bin/dmon#L3-L8

Even with the game closed the process can still be running. Didn't catch this edge case initially.

```sh
root# ps aux | grep -i "PokmonGO.app/PokmonGO" | grep -v grep
mobile         23398   0.0  0.2 408075872   3888   ??  Ss   11:45PM   0:00.50 /var/containers/Bundle/Application/42E6155C-F220-4682-9CBC-25ECAB5BD2DC/PokmonGO.app/PokmonGO
```

## Potential fix

Initially I wanted to do game detection via the proper Apple API. But no matter what I try I always get `null` as the output. Tried a few different varaiations in the following file to get `[(SpringBoard *)UIApplication.sharedApplication _accessibilityFrontMostApplication];` to work but never got anything usable.

https://github.com/clburlison/dmon/blob/current_app/tools/current_app.m

https://www.reddit.com/r/jailbreakdevelopers/comments/q9d0w4/comment/hgv41k9/?utm_source=share&utm_medium=web2x&context=3

**Comment by clburlison** [comment]
Until this bug is fixed I still recommend using SAM.

**Comment by jorgschulze73** [comment]
I think `_accessibilityFrontMostApplication` only works if you're running from Springboard process itself.

Otherwise it should be possible to get bundle identifier of frontmost application using `SpringBoardServices` framework:
https://stackoverflow.com/questions/25939616/how-to-get-frontmost-app-is-ios8

**Comment by clburlison** [comment]
ChatGPT for the win. Thanks for the tip.
```
NSString * getFrontMostApplication() {
    
    mach_port_t p = SBSSpringBoardServerPort();
    char frontmostAppS[256];
    memset(frontmostAppS, 0, sizeof(frontmostAppS));
    SBFrontmostApplicationDisplayIdentifier(p,frontmostAppS);
    
    NSString * frontmostApp = [NSString stringWithFormat:@"%s",frontmostAppS];
    NSLog(@"Frontmost app is %@", frontmostApp);
    return (frontmostApp);
}
```

The above looks to be working consistently just need to get this merged into a usable binary.
